/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-10-21 10:21:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.Main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Main.NursingHospital.model.ov.NursingHospital;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Main.NursingHospital.model.ov.NursingHospital");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	NursingHospital loginHospital = (NursingHospital)session.getAttribute("loginHospital");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"h-100\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\r\n");
      out.write("    <title>NHMP</title>\r\n");
      out.write("    <!-- Favicon icon -->\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"/NHMP/resources/ERP/images/assets/favicon.png\">\r\n");
      out.write("    <!-- <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.5.0/css/all.css\" integrity=\"sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU\" crossorigin=\"anonymous\"> -->\r\n");
      out.write("    <link href=\"/NHMP/resources/ERP/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"h-100\">\r\n");
      out.write("    \r\n");
      out.write("    <!--*******************\r\n");
      out.write("        Preloader start\r\n");
      out.write("    ********************-->\r\n");
      out.write("    <div id=\"preloader\">\r\n");
      out.write("        <div class=\"loader\">\r\n");
      out.write("            <svg class=\"circular\" viewBox=\"25 25 50 50\">\r\n");
      out.write("                <circle class=\"path\" cx=\"50\" cy=\"50\" r=\"20\" fill=\"none\" stroke-width=\"3\" stroke-miterlimit=\"10\" />\r\n");
      out.write("            </svg>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--*******************\r\n");
      out.write("        Preloader end\r\n");
      out.write("    ********************-->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"login-form-bg h-100\">\r\n");
      out.write("        <div class=\"container h-100\">\r\n");
      out.write("            <div class=\"row justify-content-center h-100\">\r\n");
      out.write("                <div class=\"col-xl-6\">\r\n");
      out.write("                    <div class=\"form-input-content\">\r\n");
      out.write("                        <div class=\"card login-form mb-0\">\r\n");
      out.write("                            <div class=\"card-body pt-5\">\r\n");
      out.write("                                <a class=\"text-center\" href=\"/NHMP/index.jsp\"> <h4>NHMP</h4></a>\r\n");
      out.write("        \t\t\t\t\t\t");
 if(loginHospital != null) {
      out.write("\r\n");
      out.write("        \t\t\t\t\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print( loginHospital.getNH_NAME() );
      out.write("님,<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t메일 0 개&nbsp; &nbsp; &nbsp; 쪽지 0 개<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- 쿼리스트링을 이용하여 값을 전달 (?이름=값) -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"/NHMP/myinfo?userid=");
      out.print( loginHospital.getNH_USERID() );
      out.write("\">상세정보</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp; &nbsp; &nbsp; &nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"/NHMP/index.jsp\">홈으로</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp; &nbsp; &nbsp; &nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"/NHMP/logout\">로그아웃</a> <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("        \t\t\t\t\t\t");
 }else {
      out.write("\r\n");
      out.write("        \t\t\t\t\t\t\t<form class=\"mt-5 mb-5 login-input\" action=\"/NHMP/login\" method=\"post\">\r\n");
      out.write("                                 \t  \t<div class=\"form-group\">\r\n");
      out.write("                            \t            <input type=\"text\" name=\"userid\"class=\"form-control\" placeholder=\"userID\">\r\n");
      out.write("                              \t     \t</div>\r\n");
      out.write("                             \t      \t<div class=\"form-group\">\r\n");
      out.write("                              \t        \t<input type=\"password\" name=\"userpwd\"class=\"form-control\" placeholder=\"Password\">\r\n");
      out.write("                             \t      \t</div>\r\n");
      out.write("                           \t        \t<button class=\"btn login-form__btn submit w-100\">로그인</button>\r\n");
      out.write("                          \t     \t</form>\r\n");
      out.write("\t                                <div align=\"right\">\r\n");
      out.write("\t                                \t비밀번호 몰라?<a href=\"page-register.html\" class=\"text-primary\">여기로</a> 이동~\r\n");
      out.write("\t                                </div>\r\n");
      out.write("\t                                <div align=\"right\">\r\n");
      out.write("\t                                \t<a id=\"signup\" href=\"/NHMP/views/Main/singup.jsp\" style=\"text-align:left\" >회원가입</a>\r\n");
      out.write("\t                                </div>\r\n");
      out.write("        \t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!--**********************************\r\n");
      out.write("        Scripts\r\n");
      out.write("    ***********************************-->\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/css/plugins/common/common.min.js\"></script>\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/js/custom.min.js\"></script>\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/js/settings.js\"></script>\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/js/gleek.js\"></script>\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/js/styleSwitcher.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
