/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-10-26 08:09:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.ERP.Cauthority;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import ERP.Cauthority.model.vo.Cauthority;

public final class CauthorityList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ERP.Cauthority.model.vo.Cauthority");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	ArrayList<Cauthority> list = (ArrayList<Cauthority>)request.getAttribute("list");

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\r\n");
      out.write("    <title>TMTS</title>\r\n");
      out.write("    <!-- Favicon icon -->\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"/NHMP/resources/ERP/images/common/favicon.png\">\r\n");
      out.write("    <!-- Pignose Calender -->\r\n");
      out.write("    <link href=\"/NHMP/resources/ERP/css/plugins/pg-calendar/css/pignose.calendar.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Chartist -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/NHMP/resources/ERP/css/plugins/chartist/css/chartist.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/NHMP/resources/ERP/css/plugins/chartist-plugin-tooltips/css/chartist-plugin-tooltip.css\">\r\n");
      out.write("    <!-- Custom Stylesheet -->\r\n");
      out.write("    <link href=\"/NHMP/resources/ERP/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!--*******************\r\n");
      out.write("        Preloader start\r\n");
      out.write("    ********************-->\r\n");
      out.write("    <div id=\"preloader\">\r\n");
      out.write("        <div class=\"loader\">\r\n");
      out.write("            <svg class=\"circular\" viewBox=\"25 25 50 50\">\r\n");
      out.write("                <circle class=\"path\" cx=\"50\" cy=\"50\" r=\"20\" fill=\"none\" stroke-width=\"3\" stroke-miterlimit=\"10\" />\r\n");
      out.write("            </svg>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--*******************\r\n");
      out.write("        Preloader end\r\n");
      out.write("    ********************-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--**********************************\r\n");
      out.write("        Main wrapper start\r\n");
      out.write("    ***********************************-->\r\n");
      out.write("    <div id=\"main-wrapper\">\r\n");
      out.write("\r\n");
      out.write("        <!--**********************************\r\n");
      out.write("            Nav header start\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("        <div class=\"nav-header\">\r\n");
      out.write("            <div class=\"brand-logo\">\r\n");
      out.write("                <a href=\"index.html\">\r\n");
      out.write("                    <b class=\"logo-abbr\"><img src=\"/NHMP/resources/ERP/images/common/logo.png\" alt=\"\"> </b>\r\n");
      out.write("                    <span class=\"logo-compact\"><img src=\"/NHMP/resources/ERP/images/common/logo-compact.png\" alt=\"\"></span>\r\n");
      out.write("                    <span class=\"brand-title\">\r\n");
      out.write("                        <img align=\"middle\" src=\"/NHMP/resources/ERP/images/common/logo-text.png\" ailgn=\"\">\r\n");
      out.write("                    </span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--**********************************\r\n");
      out.write("            Nav header end\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\r\n");
      out.write("        <!--**********************************\r\n");
      out.write("            Header start\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <div class=\"header-content clearfix\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"nav-control\">\r\n");
      out.write("                    <div class=\"hamburger\">\r\n");
      out.write("                        <span class=\"toggle-icon\"><i class=\"icon-menu\"></i></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"header-left\">\r\n");
      out.write("                    <div class=\"input-group icons\">\r\n");
      out.write("                        <div class=\"input-group-prepend\">\r\n");
      out.write("                            <span class=\"input-group-text bg-transparent border-0 pr-2 pr-sm-3\" id=\"basic-addon1\"><i class=\"mdi mdi-magnify\"></i></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <input type=\"search\" class=\"form-control\" placeholder=\"검색할 메뉴 명\" aria-label=\"Search Dashboard\">\r\n");
      out.write("                        <div class=\"drop-down animated flipInX d-md-none\">\r\n");
      out.write("                            <form action=\"#\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" placeholder=\"Search\">\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"header-right\">\r\n");
      out.write("                    <ul class=\"clearfix\">\r\n");
      out.write("                        <li class=\"icons dropdown\"><a href=\"javascript:void(0)\" data-toggle=\"dropdown\">\r\n");
      out.write("                                <i class=\"mdi mdi-email-outline\"></i>\r\n");
      out.write("                                <span class=\"badge badge-pill gradient-1\">3</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"drop-down animated fadeIn dropdown-menu\">\r\n");
      out.write("                                <div class=\"dropdown-content-heading d-flex justify-content-between\">\r\n");
      out.write("                                    <span class=\"\">3 New Messages</span>\r\n");
      out.write("                                    <a href=\"javascript:void()\" class=\"d-inline-block\">\r\n");
      out.write("                                        <span class=\"badge badge-pill gradient-1\">3</span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"dropdown-content-body\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li class=\"notification-unread\">\r\n");
      out.write("                                            <a href=\"javascript:void()\">\r\n");
      out.write("                                                <img class=\"float-left mr-3 avatar-img\" src=\"/NHMP/resources/ERP/images/avatar/1.jpg\" alt=\"\">\r\n");
      out.write("                                                <div class=\"notification-content\">\r\n");
      out.write("                                                    <div class=\"notification-heading\">Saiful Islam</div>\r\n");
      out.write("                                                    <div class=\"notification-timestamp\">08 Hours ago</div>\r\n");
      out.write("                                                    <div class=\"notification-text\">Hi Teddy, Just wanted to let you ...</div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"notification-unread\">\r\n");
      out.write("                                            <a href=\"javascript:void()\">\r\n");
      out.write("                                                <img class=\"float-left mr-3 avatar-img\" src=\"/NHMP/resources/ERP/images/avatar/2.jpg\" alt=\"\">\r\n");
      out.write("                                                <div class=\"notification-content\">\r\n");
      out.write("                                                    <div class=\"notification-heading\">Adam Smith</div>\r\n");
      out.write("                                                    <div class=\"notification-timestamp\">08 Hours ago</div>\r\n");
      out.write("                                                    <div class=\"notification-text\">Can you do me a favour?</div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"javascript:void()\">\r\n");
      out.write("                                                <img class=\"float-left mr-3 avatar-img\" src=\"/NHMP/resources/ERP/images/avatar/3.jpg\" alt=\"\">\r\n");
      out.write("                                                <div class=\"notification-content\">\r\n");
      out.write("                                                    <div class=\"notification-heading\">Barak Obama</div>\r\n");
      out.write("                                                    <div class=\"notification-timestamp\">08 Hours ago</div>\r\n");
      out.write("                                                    <div class=\"notification-text\">Hi Teddy, Just wanted to let you ...</div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"javascript:void()\">\r\n");
      out.write("                                                <img class=\"float-left mr-3 avatar-img\" src=\"/NHMP/resources/ERP/images/avatar/4.jpg\" alt=\"\">\r\n");
      out.write("                                                <div class=\"notification-content\">\r\n");
      out.write("                                                    <div class=\"notification-heading\">Hilari Clinton</div>\r\n");
      out.write("                                                    <div class=\"notification-timestamp\">08 Hours ago</div>\r\n");
      out.write("                                                    <div class=\"notification-text\">Hello</div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"icons dropdown\"><a href=\"javascript:void(0)\" data-toggle=\"dropdown\">\r\n");
      out.write("                                <i class=\"mdi mdi-bell-outline\"></i>\r\n");
      out.write("                                <span class=\"badge badge-pill gradient-2\">3</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"drop-down animated fadeIn dropdown-menu dropdown-notfication\">\r\n");
      out.write("                                <div class=\"dropdown-content-heading d-flex justify-content-between\">\r\n");
      out.write("                                    <span class=\"\">2 New Notifications</span>\r\n");
      out.write("                                    <a href=\"javascript:void()\" class=\"d-inline-block\">\r\n");
      out.write("                                        <span class=\"badge badge-pill gradient-2\">5</span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"dropdown-content-body\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"javascript:void()\">\r\n");
      out.write("                                                <span class=\"mr-3 avatar-icon bg-success-lighten-2\"><i class=\"icon-present\"></i></span>\r\n");
      out.write("                                                <div class=\"notification-content\">\r\n");
      out.write("                                                    <h6 class=\"notification-heading\">Events near you</h6>\r\n");
      out.write("                                                    <span class=\"notification-text\">Within next 5 days</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"javascript:void()\">\r\n");
      out.write("                                                <span class=\"mr-3 avatar-icon bg-danger-lighten-2\"><i class=\"icon-present\"></i></span>\r\n");
      out.write("                                                <div class=\"notification-content\">\r\n");
      out.write("                                                    <h6 class=\"notification-heading\">Event Started</h6>\r\n");
      out.write("                                                    <span class=\"notification-text\">One hour ago</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"javascript:void()\">\r\n");
      out.write("                                                <span class=\"mr-3 avatar-icon bg-success-lighten-2\"><i class=\"icon-present\"></i></span>\r\n");
      out.write("                                                <div class=\"notification-content\">\r\n");
      out.write("                                                    <h6 class=\"notification-heading\">Event Ended Successfully</h6>\r\n");
      out.write("                                                    <span class=\"notification-text\">One hour ago</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"javascript:void()\">\r\n");
      out.write("                                                <span class=\"mr-3 avatar-icon bg-danger-lighten-2\"><i class=\"icon-present\"></i></span>\r\n");
      out.write("                                                <div class=\"notification-content\">\r\n");
      out.write("                                                    <h6 class=\"notification-heading\">Events to Join</h6>\r\n");
      out.write("                                                    <span class=\"notification-text\">After two days</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"icons dropdown d-none d-md-flex\">\r\n");
      out.write("                            <a href=\"javascript:void(0)\" class=\"log-user\"  data-toggle=\"dropdown\">\r\n");
      out.write("                                <span>korean</span>  <i class=\"fa fa-angle-down f-s-14\" aria-hidden=\"true\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"drop-down dropdown-language animated fadeIn  dropdown-menu\">\r\n");
      out.write("                                <div class=\"dropdown-content-body\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"javascript:void()\">English</a></li>\r\n");
      out.write("                                        <li><a href=\"javascript:void()\">Korean</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"icons dropdown\">\r\n");
      out.write("                            <div class=\"user-img c-pointer position-relative\"   data-toggle=\"dropdown\">\r\n");
      out.write("                                <span class=\"activity active\"></span>\r\n");
      out.write("                                <img src=\"/NHMP/resources/ERP/images/user/1.png\" height=\"40\" width=\"40\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"drop-down dropdown-profile animated fadeIn dropdown-menu\">\r\n");
      out.write("                                <div class=\"dropdown-content-body\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"app-profile.html\"><i class=\"icon-user\"></i> <span>마이페이지</span></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"javascript:void()\">\r\n");
      out.write("                                                <i class=\"icon-envelope-open\"></i> <span>Inbox</span> <div class=\"badge gradient-3 badge-pill gradient-1\">3</div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("\r\n");
      out.write("                                        <hr class=\"my-2\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"page-lock.html\"><i class=\"icon-lock\"></i> <span>Lock Screen</span></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li><a href=\"page-login.html\"><i class=\"icon-key\"></i> <span>Logout</span></a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--**********************************\r\n");
      out.write("            Header end ti-comment-alt\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\r\n");
      out.write("        <!--**********************************\r\n");
      out.write("            Sidebar start\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("        <div class=\"nk-sidebar\">\r\n");
      out.write("            <div class=\"nk-nav-scroll\">\r\n");
      out.write("                <ul class=\"metismenu\" id=\"menu\">\r\n");
      out.write("                    <li class=\"mega-menu mega-menu-sm\">\r\n");
      out.write("                        <a class=\"has-arrow\" href=\"javascript:void()\" aria-expanded=\"false\">\r\n");
      out.write("                                <i class=\"fa fa-users\"></i><span class=\"nav-text\">인사관리</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul aria-expanded=\"false\">\r\n");
      out.write("                            <li><a href=\"layout-blank.html\">인사정보관리</a></li>\r\n");
      out.write("                            <li><a href=\"layout-one-column.html\">인사정보등록</a></li>\r\n");
      out.write("                            <li><a href=\"layout-two-column.html\">조직도</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"has-arrow\" href=\"javascript:void()\" aria-expanded=\"false\">\r\n");
      out.write("                            <i class=\"fa fa-id-card\"></i> <span class=\"nav-text\">권한설정</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul aria-expanded=\"false\">\r\n");
      out.write("                            <li><a href=\"/NHMP/authall\">권한부여관리</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"has-arrow\" href=\"javascript:void()\" aria-expanded=\"false\">\r\n");
      out.write("                                <i class=\"fa fa-plus-square\"></i><span class=\"nav-text\">환자 관리</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("\r\n");
      out.write("                        <ul aria-expanded=\"false\">\r\n");
      out.write("                            <li><a href=\"app-profile.html\">전체환자 조회</a></li>\r\n");
      out.write("                            <li><a href=\"app-calender.html\">환자 입원 등록</a></li>\r\n");
      out.write("                            <li><a href=\"app-calender.html\">상담일지 등록</a></li>\r\n");
      out.write("                            <li><a href=\"app-calender.html\">투약일지 등록</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("               \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"has-arrow\" href=\"javascript:void()\" aria-expanded=\"false\">\r\n");
      out.write("                                <i class=\"fa fa-usd\"></i><span class=\"nav-text\">급여 관리</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul aria-expanded=\"false\">\r\n");
      out.write("                            <li><a href=\"ui-accordion.html\">공제항목등록</a></li>\r\n");
      out.write("                            <li><a href=\"ui-alert.html\">수당항목등록</a></li>\r\n");
      out.write("                            <li><a href=\"ui-badge.html\">급여계산</a></li>\r\n");
      out.write("                           \r\n");
      out.write("                  </ul>\r\n");
      out.write("                  <li>\r\n");
      out.write("                          <a href=\"javascript:void()\" aria-expanded=\"false\">\r\n");
      out.write("                                  <i class=\"fa fa-slideshare\"></i> <span class=\"nav-text\">공지사항</span>\r\n");
      out.write("                          </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                          <a href=\"javascript:void()\" aria-expanded=\"false\">\r\n");
      out.write("                                  <i class=\"fa fa-download\"></i> <span class=\"nav-text\">자료실</span>\r\n");
      out.write("                          </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("               </div>\r\n");
      out.write("           </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!--**********************************\r\n");
      out.write("            Sidebar end\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\r\n");
      out.write("        <!--**********************************\r\n");
      out.write("            Content body start\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("        <div class=\"content-body\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"container-fluid mt-3\">\r\n");
      out.write("            \t<h2 align=\"center\">전체 권한 목록 : 총 ");
      out.print( list.size() );
      out.write("개</h2>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-12\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                            <table align=\"right\">\r\n");
      out.write("                            \t<td align=\"right\">\r\n");
      out.write("                            \t\t<a href=\"#\"><input type=\"button\" value=\"추가\"></a> &nbsp; &nbsp; \r\n");
      out.write("                            \t\t<a href=\"#\"><input type=\"button\" value=\"삭제\"></a> &nbsp; &nbsp; \r\n");
      out.write("                            \t</td>\r\n");
      out.write("                            </table>\r\n");
      out.write("                            \t\r\n");
      out.write("                            \r\n");
      out.write("                                <div class=\"active-member\">\r\n");
      out.write("                                    <div class=\"table-responsive\">\r\n");
      out.write("                                        <table class=\"table table-xs mb-0\">\r\n");
      out.write("                                            \r\n");
      out.write("                                            <thead>\r\n");
      out.write("                                                <tr>\r\n");
      out.write("                                                    <th>사용자</th>\r\n");
      out.write("                                                    <th>접속기기</th>\r\n");
      out.write("                                                    <th>접속지역</th>\r\n");
      out.write("                                                    <th>지위</th>\r\n");
      out.write("                                                    <th>결제방법</th>\r\n");
      out.write("                                                    <th>활동</th>\r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                            </thead>\r\n");
      out.write("                                            <tbody>\r\n");
      out.write("                                                <tr>\r\n");
      out.write("                                                    <td><img src=\"/NHMP/resources/ERP/images/avatar/1.jpg\" class=\" rounded-circle mr-3\" alt=\"\">Sarah Smith</td>\r\n");
      out.write("                                                    <td>iPhone X</td>\r\n");
      out.write("                                                    <td>\r\n");
      out.write("                                                        <span>United States</span>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td>\r\n");
      out.write("                                                        <div>\r\n");
      out.write("                                                            <div class=\"progress\" style=\"height: 6px\">\r\n");
      out.write("                                                                <div class=\"progress-bar bg-success\" style=\"width: 50%\"></div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td><i class=\"fa fa-circle-o text-success  mr-2\"></i> Paid</td>\r\n");
      out.write("                                                    <td>\r\n");
      out.write("                                                        <span>Last Login</span>\r\n");
      out.write("                                                        <span class=\"m-0 pl-3\">10 sec ago</span>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                                <tr>\r\n");
      out.write("                                                    <td><img src=\"/NHMP/resources/ERP/images/avatar/2.jpg\" class=\" rounded-circle mr-3\" alt=\"\">Walter R.</td>\r\n");
      out.write("                                                    <td>Pixel 2</td>\r\n");
      out.write("                                                    <td><span>Canada</span></td>\r\n");
      out.write("                                                    <td>\r\n");
      out.write("                                                        <div>\r\n");
      out.write("                                                            <div class=\"progress\" style=\"height: 6px\">\r\n");
      out.write("                                                                <div class=\"progress-bar bg-success\" style=\"width: 50%\"></div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td><i class=\"fa fa-circle-o text-success  mr-2\"></i> Paid</td>\r\n");
      out.write("                                                    <td>\r\n");
      out.write("                                                        <span>Last Login</span>\r\n");
      out.write("                                                        <span class=\"m-0 pl-3\">50 sec ago</span>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                                <tr>\r\n");
      out.write("                                                    <td><img src=\"/NHMP/resources/ERP/images/avatar/3.jpg\" class=\" rounded-circle mr-3\" alt=\"\">Andrew D.</td>\r\n");
      out.write("                                                    <td>OnePlus</td>\r\n");
      out.write("                                                    <td><span>Germany</span></td>\r\n");
      out.write("                                                    <td>\r\n");
      out.write("                                                        <div>\r\n");
      out.write("                                                            <div class=\"progress\" style=\"height: 6px\">\r\n");
      out.write("                                                                <div class=\"progress-bar bg-warning\" style=\"width: 50%\"></div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td><i class=\"fa fa-circle-o text-warning  mr-2\"></i> Pending</td>\r\n");
      out.write("                                                    <td>\r\n");
      out.write("                                                        <span>Last Login</span>\r\n");
      out.write("                                                        <span class=\"m-0 pl-3\">10 sec ago</span>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                                <tr>\r\n");
      out.write("                                                    <td><img src=\"/NHMP/resources/ERP/images/avatar/6.jpg\" class=\" rounded-circle mr-3\" alt=\"\"> Megan S.</td>\r\n");
      out.write("                                                    <td>Galaxy</td>\r\n");
      out.write("                                                    <td><span>Japan</span></td>\r\n");
      out.write("                                                    <td>\r\n");
      out.write("                                                        <div>\r\n");
      out.write("                                                            <div class=\"progress\" style=\"height: 6px\">\r\n");
      out.write("                                                                <div class=\"progress-bar bg-success\" style=\"width: 50%\"></div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td><i class=\"fa fa-circle-o text-success  mr-2\"></i> Paid</td>\r\n");
      out.write("                                                    <td>\r\n");
      out.write("                                                        <span>Last Login</span>\r\n");
      out.write("                                                        <span class=\"m-0 pl-3\">10 sec ago</span>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                                <tr>\r\n");
      out.write("                                                    <td><img src=\"/NHMP/resources/ERP/images/avatar/4.jpg\" class=\" rounded-circle mr-3\" alt=\"\"> Doris R.</td>\r\n");
      out.write("                                                    <td>Moto Z2</td>\r\n");
      out.write("                                                    <td><span>England</span></td>\r\n");
      out.write("                                                    <td>\r\n");
      out.write("                                                        <div>\r\n");
      out.write("                                                            <div class=\"progress\" style=\"height: 6px\">\r\n");
      out.write("                                                                <div class=\"progress-bar bg-success\" style=\"width: 50%\"></div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td><i class=\"fa fa-circle-o text-success  mr-2\"></i> Paid</td>\r\n");
      out.write("                                                    <td>\r\n");
      out.write("                                                        <span>Last Login</span>\r\n");
      out.write("                                                        <span class=\"m-0 pl-3\">10 sec ago</span>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                                <tr>\r\n");
      out.write("                                                    <td><img src=\"/NHMP/resources/ERP/images/avatar/5.jpg\" class=\" rounded-circle mr-3\" alt=\"\">Elizabeth W.</td>\r\n");
      out.write("                                                    <td>Notebook Asus</td>\r\n");
      out.write("                                                    <td><span>China</span></td>\r\n");
      out.write("                                                    <td>\r\n");
      out.write("                                                        <div>\r\n");
      out.write("                                                            <div class=\"progress\" style=\"height: 6px\">\r\n");
      out.write("                                                                <div class=\"progress-bar bg-warning\" style=\"width: 50%\"></div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td><i class=\"fa fa-circle-o text-warning  mr-2\"></i> Pending</td>\r\n");
      out.write("                                                    <td>\r\n");
      out.write("                                                        <span>Last Login</span>\r\n");
      out.write("                                                        <span class=\"m-0 pl-3\">10 sec ago</span>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                            </tbody>\r\n");
      out.write("                                        </table>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            <!-- #/ container -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--**********************************\r\n");
      out.write("            Content body end\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!--**********************************\r\n");
      out.write("            Footer start\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("        <div class=\"footer\">\r\n");
      out.write("            <div class=\"copyright\">\r\n");
      out.write("                <p>Copyright &copy; Designed & Developed by <a href=\"https://themeforest.net/user/quixlab\">이민삼수</a> 2019</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--**********************************\r\n");
      out.write("            Footer end\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--**********************************\r\n");
      out.write("        Main wrapper end\r\n");
      out.write("    ***********************************-->\r\n");
      out.write("\r\n");
      out.write("    <!--**********************************\r\n");
      out.write("        Scripts\r\n");
      out.write("    ***********************************-->\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/css/plugins/common/common.min.js\"></script>\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/js/custom.min.js\"></script>\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/js/settings.js\"></script>\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/js/gleek.js\"></script>\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/js/styleSwitcher.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Chartjs -->\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/css/plugins/chart.js/Chart.bundle.min.js\"></script>\r\n");
      out.write("    <!-- Circle progress -->\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/css/plugins/circle-progress/circle-progress.min.js\"></script>\r\n");
      out.write("    <!-- Datamap -->\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/css/plugins/d3v3/index.js\"></script>\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/css/plugins/topojson/topojson.min.js\"></script>\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/css/plugins/datamaps/datamaps.world.min.js\"></script>\r\n");
      out.write("    <!-- Morrisjs -->\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/css/plugins/raphael/raphael.min.js\"></script>\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/css/plugins/morris/morris.min.js\"></script>\r\n");
      out.write("    <!-- Pignose Calender -->\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/css/plugins/moment/moment.min.js\"></script>\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/css/plugins/pg-calendar/js/pignose.calendar.min.js\"></script>\r\n");
      out.write("    <!-- ChartistJS -->\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/css/plugins/chartist/js/chartist.min.js\"></script>\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/css/plugins/chartist-plugin-tooltips/js/chartist-plugin-tooltip.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"/NHMP/resources/ERP/js/dashboard-1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
