/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-10-18 06:09:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Main.NursingHospital.model.ov.NursingHospital;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Main.NursingHospital.model.ov.NursingHospital");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	NursingHospital loginHospital = (NursingHospital)session.getAttribute("loginHospital");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>HOME</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,600,700\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/NHMP/resources/Main/css/open-iconic-bootstrap.min.css?after\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/NHMP/resources/Main/css/animate.css?after\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/NHMP/resources/Main/css/owl.carousel.min.css?after\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/NHMP/resources/Main/css/owl.theme.default.min.css?after\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/NHMP/resources/Main/css/magnific-popup.css?after\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/NHMP/resources/Main/css/aos.css?after\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/NHMP/resources/Main/css/ionicons.min.css?after\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/NHMP/resources/Main/css/bootstrap-datepicker.css?after\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/NHMP/resources/Main/css/jquery.timepicker.css?after\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/NHMP/resources/Main/css/flaticon.css?after\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/NHMP/resources/Main/css/icomoon.css?after\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/NHMP/resources/Main/css/style.css?after\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("          <nav class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\" id=\"ftco-navbar\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("              <a class=\"navbar-brand\" href=\"/NHMP/index.jsp\">이 민 삼 수</a>\r\n");
      out.write("              <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("              </button>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("                <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                  <li class=\"nav-item active\"><a href=\"index.jsp\" class=\"nav-link\">Home</a></li>\r\n");
      out.write("                  <!--  <li class=\"nav-item\"><a href=\"views/main/about.html\" class=\"nav-link\">About</a></li> -->\r\n");
      out.write("                  <li class=\"nav-item\"><a href=\"/NHMP/views/Main/domain.jsp\" class=\"nav-link\">서비스 소개</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"><a href=\"/NHMP/views/Main/hosting.jsp\" class=\"nav-link\" >기능소개</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"><a href=\"/NHMP/views/Main/blog.jsp\" class=\"nav-link\">온라인 고객센터</a></li>\r\n");
      out.write("                  <li class=\"nav-item\"><a href=\"/NHMP/views/Main/contact.jsp\" class=\"nav-link\">이민삼수 소개</a></li>\r\n");
      out.write("                  ");
 if(loginHospital == null) { //미 로그인
      out.write("\r\n");
      out.write("                  \t<li class=\"nav-item\"><a href=\"/NHMP/views/Main/login.jsp\" class=\"nav-link\"><span>로그인</span></a></li>\r\n");
      out.write("                  ");
 } else if ( loginHospital.getNH_USERID().equals("admin") ) {	//관리자 로그인
      out.write(" \r\n");
      out.write("                  \t<li class=\"nav-item\">\r\n");
      out.write("                  \t\t<a href=\"/NHMP/views/Main/login.jsp\" class=\"nav-link\">\r\n");
      out.write("                  \t\t<span>내정보</span></a>\r\n");
      out.write("                  \t\t<li class=\"nav-item cta\"><a href=\"/NHMP/views/ERP/Admin_main.jsp\" class=\"nav-link\"><span>시스템 관리</span></a></li>\r\n");
      out.write("                  \t</li>\r\n");
      out.write("                  ");
 } else { //일반 로그인
      out.write("\r\n");
      out.write("                  \t<li class=\"nav-item\">\r\n");
      out.write("                  \t\t<a href=\"/NHMP/views/Main/login.jsp\" class=\"nav-link\">\r\n");
      out.write("                  \t\t<span>내정보</span></a>\r\n");
      out.write("                  \t\t<li class=\"nav-item cta\"><a href=\"/NHMP/views/ERP/main.jsp\" class=\"nav-link\"><span>시스템 관리</span></a></li>\r\n");
      out.write("                  \t</li>\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </nav>\r\n");
      out.write("    <!-- END nav -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"hero-wrap js-fullheight img\" style=\"background-image: url(/NHMP/resources/Main/images/bg_1.jpg);\">\r\n");
      out.write("      <div class=\"overlay\"></div>\r\n");
      out.write("      <div class=\"container-fluid px-0\">\r\n");
      out.write("        <div class=\"row d-md-flex no-gutters slider-text align-items-center js-fullheight justify-content-center\">\r\n");
      out.write("                <div class=\"col-md-8 text-center d-flex align-items-center ftco-animate js-fullheight\">\r\n");
      out.write("                        <div class=\"text mt-5\">\r\n");
      out.write("                                <span class=\"subheading\">클라우드 ERP</span>\r\n");
      out.write("                    <h1 class=\"mb-3\">The Best Cloud ERP System</h1>\r\n");
      out.write("                    <p>최고의 클라우드 ERP 시스템을 경험해 보세요!</p>\r\n");
      out.write("                 <!--   <p><a href=\"#\" class=\"btn btn-secondary px-4 py-3\">Get Started Now</a></p> -->\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("<!-- \r\n");
      out.write("    <section class=\"ftco-domain\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("                <div class=\"row d-flex align-items-center justify-content-center\">\r\n");
      out.write("                        <div class=\"col-lg-10 p-5 ftco-wrap ftco-animate\">\r\n");
      out.write("                                <form action=\"#\" class=\"domain-form d-flex mb-3\">\r\n");
      out.write("              <div class=\"form-group domain-name\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control name px-4\" placeholder=\"Enter your domain name...\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group domain-select d-flex\">\r\n");
      out.write("                      <div class=\"select-wrap\">\r\n");
      out.write("                  <div class=\"icon\"><span class=\"ion-ios-arrow-down\"></span></div>\r\n");
      out.write("                  <select name=\"\" id=\"\" class=\"form-control\">\r\n");
      out.write("                    <option value=\"\">.com</option>\r\n");
      out.write("                    <option value=\"\">.net</option>\r\n");
      out.write("                    <option value=\"\">.biz</option>\r\n");
      out.write("                    <option value=\"\">.co</option>\r\n");
      out.write("                    <option value=\"\">.me</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <input type=\"submit\" class=\"search-domain btn btn-primary text-center\" value=\"Search\">\r\n");
      out.write("                    </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <p class=\"domain-price mt-2 text-center\">\r\n");
      out.write("                <span><small>.com</small> $9.75</span>\r\n");
      out.write("                <span><small>.net</small> $9.50</span>\r\n");
      out.write("                <span><small>.biz</small> $8.95</span>\r\n");
      out.write("                <span><small>.co</small> $7.80</span>\r\n");
      out.write("                <span><small>.me</small> $7.95</span>\r\n");
      out.write("            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write(" --> \r\n");
      out.write(" <!--    \r\n");
      out.write(" \t<section class=\"ftco-section ftco-partner\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-sm ftco-animate\">\r\n");
      out.write("                                <a href=\"#\" class=\"partner\"><img src=\"/NHMP/resources/Main/images/partner-1.png\" class=\"img-fluid\" alt=\"Colorlib Template\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm ftco-animate\">\r\n");
      out.write("                                <a href=\"#\" class=\"partner\"><img src=\"/NHMP/resources/Main/images/partner-2.png\" class=\"img-fluid\" alt=\"Colorlib Template\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm ftco-animate\">\r\n");
      out.write("                                <a href=\"#\" class=\"partner\"><img src=\"/NHMP/resources/Main/images/partner-3.png\" class=\"img-fluid\" alt=\"Colorlib Template\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm ftco-animate\">\r\n");
      out.write("                                <a href=\"#\" class=\"partner\"><img src=\"/NHMP/resources/Main/images/partner-4.png\" class=\"img-fluid\" alt=\"Colorlib Template\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm ftco-animate\">\r\n");
      out.write("                                <a href=\"#\" class=\"partner\"><img src=\"/NHMP/resources/Main/images/partner-5.png\" class=\"img-fluid\" alt=\"Colorlib Template\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write(" -->\r\n");
      out.write(" \r\n");
      out.write(" <!--    <section class=\"ftco-section services-section bg-light ftco-no-pb\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row justify-content-center mb-5 pb-3\">\r\n");
      out.write("          <div class=\"col-md-7 text-center heading-section ftco-animate\">\r\n");
      out.write("            <h2 class=\"mb-4\">Why You Should Choose Us</h2>\r\n");
      out.write("            <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-4 d-flex align-self-stretch ftco-animate\">\r\n");
      out.write("            <div class=\"media block-6 services d-flex align-items-start\">\r\n");
      out.write("                <div class=\"icon d-flex align-items-center justify-content-center\">\r\n");
      out.write("                        <span class=\"flaticon-cloud\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("              <div class=\"media-body pl-4\">\r\n");
      out.write("                <h3 class=\"heading\">Super Fast Server</h3>\r\n");
      out.write("                <p class=\"mb-0\">Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-4 d-flex align-self-stretch ftco-animate\">\r\n");
      out.write("            <div class=\"media block-6 services d-flex align-items-start\">\r\n");
      out.write("                <div class=\"icon d-flex align-items-center justify-content-center\">\r\n");
      out.write("                        <span class=\"flaticon-server\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("              <div class=\"media-body pl-4\">\r\n");
      out.write("                <h3 class=\"heading\">Daily Backups</h3>\r\n");
      out.write("                <p class=\"mb-0\">Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-4 d-flex align-self-stretch ftco-animate\">\r\n");
      out.write("            <div class=\"media block-6 services d-flex align-items-start\">\r\n");
      out.write("                <div class=\"icon d-flex align-items-center justify-content-center\">\r\n");
      out.write("                        <span class=\"flaticon-customer-service\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("              <div class=\"media-body pl-4\">\r\n");
      out.write("                <h3 class=\"heading\">Technical Services</h3>\r\n");
      out.write("                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"ftco-section ftco-counter bg-light img\" id=\"section-counter\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("                <div class=\"row justify-content-center mb-5\">\r\n");
      out.write("          <div class=\"col-md-10 text-center heading-section ftco-animate\">\r\n");
      out.write("            <h2 class=\"mb-4\">More than 12,000 websites trusted hosted</h2>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("                <div class=\"row justify-content-center\">\r\n");
      out.write("          <div class=\"col-md-3 d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("            <div class=\"block-18 text-center\">\r\n");
      out.write("              <div class=\"text\">\r\n");
      out.write("                <strong class=\"number\" data-number=\"12000\">0</strong>\r\n");
      out.write("                <span>CMS Installation</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3 d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("            <div class=\"block-18 text-center\">\r\n");
      out.write("              <div class=\"text\">\r\n");
      out.write("                <strong class=\"number\" data-number=\"100\">0</strong>\r\n");
      out.write("                <span>Awards Won</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3 d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("            <div class=\"block-18 text-center\">\r\n");
      out.write("              <div class=\"text\">\r\n");
      out.write("                <strong class=\"number\" data-number=\"10000\">0</strong>\r\n");
      out.write("                <span>Registered Domains</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3 d-flex justify-content-center counter-wrap ftco-animate\">\r\n");
      out.write("            <div class=\"block-18 text-center\">\r\n");
      out.write("              <div class=\"text\">\r\n");
      out.write("                <strong class=\"number\" data-number=\"9000\">0</strong>\r\n");
      out.write("                <span>Satisfied Customers</span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"ftco-section ftco-no-pt ftco-no-pb\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("                <div class=\"row d-flex\">\r\n");
      out.write("                        <div class=\"col-lg-6 order-lg-last d-flex\">\r\n");
      out.write("                                <div class=\"bg-primary py-md-5 d-flex align-self-stretch\">\r\n");
      out.write("                                        <div class=\"main\">\r\n");
      out.write("                                                <img src=\"/NHMP/resources/Main/images/undraw_data_report_bi6l.svg\" class=\"img-fluid svg\" alt=\"\">\r\n");
      out.write("                                                <div class=\"heading-section heading-section-white ftco-animate mt-5 px-3 px-md-5\">\r\n");
      out.write("                                    <h2 class=\"mb-4\">Our Main Services</h2>\r\n");
      out.write("                                    <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-6 py-5\">\r\n");
      out.write("                                <div class=\"row pt-md-5\">\r\n");
      out.write("                                        <div class=\"col-md-6 ftco-animate\">\r\n");
      out.write("                                                <div class=\"media block-6 services text-center\">\r\n");
      out.write("                                <div class=\"icon d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                        <span class=\"flaticon-cloud-computing\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                              <div class=\"mt-3 media-body media-body-2\">\r\n");
      out.write("                                <h3 class=\"heading\">Cloud VPS</h3>\r\n");
      out.write("                                <p>Even the all-powerful Pointing has no control about the blind texts</p>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-6 ftco-animate\">\r\n");
      out.write("                                                <div class=\"media block-6 services text-center\">\r\n");
      out.write("                                <div class=\"icon d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                        <span class=\"flaticon-cloud\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                              <div class=\"mt-3 media-body media-body-2\">\r\n");
      out.write("                                <h3 class=\"heading\">Share</h3>\r\n");
      out.write("                                <p>Even the all-powerful Pointing has no control about the blind texts</p>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-6 ftco-animate\">\r\n");
      out.write("                                                <div class=\"media block-6 services text-center\">\r\n");
      out.write("                                <div class=\"icon d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                        <span class=\"flaticon-server\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                              <div class=\"mt-3 media-body media-body-2\">\r\n");
      out.write("                                <h3 class=\"heading\">VPS</h3>\r\n");
      out.write("                                <p>Even the all-powerful Pointing has no control about the blind texts</p>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-md-6 ftco-animate\">\r\n");
      out.write("                                                <div class=\"media block-6 services text-center\">\r\n");
      out.write("                                <div class=\"icon d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                        <span class=\"flaticon-database\"></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                              <div class=\"mt-3 media-body media-body-2\">\r\n");
      out.write("                                <h3 class=\"heading\">Dedicated</h3>\r\n");
      out.write("                                <p>Even the all-powerful Pointing has no control about the blind texts</p>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("          </div>\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section> \r\n");
      out.write("    -->\r\n");
      out.write("<!-- \r\n");
      out.write("    <section class=\"ftco-section bg-primary\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("                <div class=\"row justify-content-center mb-5 pb-3\">\r\n");
      out.write("          <div class=\"col-md-7 text-center heading-section heading-section-white ftco-animate\">\r\n");
      out.write("            <h2 class=\"mb-4\">Our Best Pricing</h2>\r\n");
      out.write("            <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("                <div class=\"row no-gutters d-flex\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 ftco-animate d-flex\">\r\n");
      out.write("                  <div class=\"block-7 bg-light d-flex align-self-stretch\">\r\n");
      out.write("                    <div class=\"text-center\">\r\n");
      out.write("                            <h2 class=\"heading\">Free</h2>\r\n");
      out.write("                            <span class=\"price\"><sup>$</sup> <span class=\"number\">0<small class=\"per\">/mo</small></span>\r\n");
      out.write("                            <span class=\"excerpt d-block\">100% free. Forever</span>\r\n");
      out.write("                            <h3 class=\"heading-2 mb-3\">Enjoy All The Features</h3>\r\n");
      out.write("\r\n");
      out.write("                            <ul class=\"pricing-text mb-4\">\r\n");
      out.write("                              <li><strong>150 GB</strong> Bandwidth</li>\r\n");
      out.write("                              <li><strong>100 GB</strong> Storage</li>\r\n");
      out.write("                              <li><strong>$1.00 / GB</strong> Overages</li>\r\n");
      out.write("                              <li>All features</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-secondary d-block px-3 py-3 mb-4\">Choose Plan</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 ftco-animate d-flex\">\r\n");
      out.write("                  <div class=\"block-7 d-flex align-self-stretch\">\r\n");
      out.write("                    <div class=\"text-center\">\r\n");
      out.write("                            <h2 class=\"heading\">Startup</h2>\r\n");
      out.write("                            <span class=\"price\"><sup>$</sup> <span class=\"number\">19<small class=\"per\">/mo</small></span></span>\r\n");
      out.write("                            <span class=\"excerpt d-block\">All features are included</span>\r\n");
      out.write("                            <h3 class=\"heading-2 mb-3\">Enjoy All The Features</h3>\r\n");
      out.write("\r\n");
      out.write("                            <ul class=\"pricing-text mb-4\">\r\n");
      out.write("                              <li><strong>450 GB</strong> Bandwidth</li>\r\n");
      out.write("                              <li><strong>400 GB</strong> Storage</li>\r\n");
      out.write("                              <li><strong>$2.00 / GB</strong> Overages</li>\r\n");
      out.write("                              <li>All features</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-secondary d-block px-3 py-3 mb-4\">Choose Plan</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 ftco-animate d-flex\">\r\n");
      out.write("                  <div class=\"block-7 active d-flex align-self-stretch\">\r\n");
      out.write("                    <div class=\"text-center\">\r\n");
      out.write(" <h2 class=\"heading\">Premium</h2>\r\n");
      out.write("                            <span class=\"price\"><sup>$</sup> <span class=\"number\">49<small class=\"per\">/mo</small></span></span>\r\n");
      out.write("                            <span class=\"excerpt d-block\">All features are included</span>\r\n");
      out.write("                            <h3 class=\"heading-2 mb-3\">Enjoy All The Features</h3>\r\n");
      out.write("\r\n");
      out.write("                            <ul class=\"pricing-text mb-4\">\r\n");
      out.write("                              <li><strong>250 GB</strong> Bandwidth</li>\r\n");
      out.write("                              <li><strong>200 GB</strong> Storage</li>\r\n");
      out.write("                              <li><strong>$5.00 / GB</strong> Overages</li>\r\n");
      out.write("                              <li>All features</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-primary d-block px-3 py-3 mb-4\">Choose Plan</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 ftco-animate d-flex\">\r\n");
      out.write("                  <div class=\"block-7 d-flex align-self-stretch\">\r\n");
      out.write("                    <div class=\"text-center\">\r\n");
      out.write("                            <h2 class=\"heading\">Pro</h2>\r\n");
      out.write("                            <span class=\"price\"><sup>$</sup> <span class=\"number\">99<small class=\"per\">/mo</small></span></span>\r\n");
      out.write("                            <span class=\"excerpt d-block\">All features are included</span>\r\n");
      out.write("                            <h3 class=\"heading-2 mb-3\">Enjoy All The Features</h3>\r\n");
      out.write("\r\n");
      out.write("                            <ul class=\"pricing-text mb-4\">\r\n");
      out.write("                              <li><strong>450 GB</strong> Bandwidth</li>\r\n");
      out.write("                              <li><strong>400 GB</strong> Storage</li>\r\n");
      out.write("                              <li><strong>$20.00 / GB</strong> Overages</li>\r\n");
      out.write("                              <li>All features</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                                  <a href=\"#\" class=\"btn btn-secondary d-block px-3 py-3 mb-4\">Choose Plan</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write(" -->    \r\n");
      out.write(" \t<section class=\"ftco-section testimony-section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row justify-content-center mb-5\">\r\n");
      out.write("          <div class=\"col-md-7 text-center heading-section ftco-animate\">\r\n");
      out.write("            <h2 class=\"mb-4\">Our satisfied customer says</h2>\r\n");
      out.write("            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row ftco-animate\">\r\n");
      out.write("          <div class=\"col-md-12\">\r\n");
      out.write("            <div class=\"carousel-testimony owl-carousel ftco-owl\">\r\n");
      out.write("              <div class=\"item\">\r\n");
      out.write("                <div class=\"testimony-wrap p-4 text-center\">\r\n");
      out.write("                  <div class=\"user-img mb-4\" style=\"background-image: url(/NHMP/resources/Main/images/person_1.jpg)\">\r\n");
      out.write("                    <span class=\"quote d-flex align-items-center justify-content-center\">\r\n");
      out.write("                      <i class=\"icon-quote-left\"></i>\r\n");
      out.write("                    </span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"text\">\r\n");
      out.write("                    <p class=\"mb-4\">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("                    <p class=\"name\">Mark Web</p>\r\n");
      out.write("                    <span class=\"position\">Marketing Manager</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"item\">\r\n");
      out.write("                <div class=\"testimony-wrap p-4 text-center\">\r\n");
      out.write("                  <div class=\"user-img mb-4\" style=\"background-image: url(/NHMP/resources/Main/images/person_2.jpg)\">\r\n");
      out.write("                    <span class=\"quote d-flex align-items-center justify-content-center\">\r\n");
      out.write("                      <i class=\"icon-quote-left\"></i>\r\n");
      out.write("                    </span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"text\">\r\n");
      out.write("                    <p class=\"mb-4\">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("                    <p class=\"name\">Mark Web</p>\r\n");
      out.write("                    <span class=\"position\">Interface Designer</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"item\">\r\n");
      out.write("                <div class=\"testimony-wrap p-4 text-center\">\r\n");
      out.write("                  <div class=\"user-img mb-4\" style=\"background-image: url(/NHMP/resources/Main/images/person_3.jpg)\">\r\n");
      out.write("                    <span class=\"quote d-flex align-items-center justify-content-center\">\r\n");
      out.write("                      <i class=\"icon-quote-left\"></i>\r\n");
      out.write("                    </span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"text\">\r\n");
      out.write("                    <p class=\"mb-4\">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("                    <p class=\"name\">Mark Web</p>\r\n");
      out.write("                    <span class=\"position\">UI Designer</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"item\">\r\n");
      out.write("                <div class=\"testimony-wrap p-4 text-center\">\r\n");
      out.write("                  <div class=\"user-img mb-4\" style=\"background-image: url(/NHMP/resources/Main/images/person_1.jpg)\">\r\n");
      out.write("                    <span class=\"quote d-flex align-items-center justify-content-center\">\r\n");
      out.write("                      <i class=\"icon-quote-left\"></i>\r\n");
      out.write("                    </span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"text\">\r\n");
      out.write("                    <p class=\"mb-4\">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("                    <p class=\"name\">Mark Web</p>\r\n");
      out.write("                    <span class=\"position\">Web Developer</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"item\">\r\n");
      out.write("                <div class=\"testimony-wrap p-4 text-center\">\r\n");
      out.write("                  <div class=\"user-img mb-4\" style=\"background-image: url(/NHMP/resources/Main/images/person_1.jpg)\">\r\n");
      out.write("                    <span class=\"quote d-flex align-items-center justify-content-center\">\r\n");
      out.write("                      <i class=\"icon-quote-left\"></i>\r\n");
      out.write("                    </span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"text\">\r\n");
      out.write("                    <p class=\"mb-4\">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("                    <p class=\"name\">Mark Web</p>\r\n");
      out.write("                    <span class=\"position\">System Analyst</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("<!-- \r\n");
      out.write("    <section class=\"ftco-section bg-light\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row justify-content-center mb-5 pb-3\">\r\n");
      out.write("          <div class=\"col-md-7 text-center heading-section ftco-animate\">\r\n");
      out.write("            <h2>Recent Blog</h2>\r\n");
      out.write("            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-4 ftco-animate\">\r\n");
      out.write("            <div class=\"blog-entry\">\r\n");
      out.write("              <a href=\"/NHMP/views/main/blog-single.html\" class=\"block-20\" style=\"background-image: url(/NHMP/resources/Main/images/image_1.jpg);\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"text text-center py-3\">\r\n");
      out.write("                <div class=\"meta mb-2\">\r\n");
      out.write("                  <div><a href=\"#\">Aug 5, 2019</a></div>\r\n");
      out.write("                  <div><a href=\"#\">Admin</a></div>\r\n");
      out.write("                  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"desc\">\r\n");
      out.write("                        <h3 class=\"heading\"><a href=\"#\">Even the all-powerful Pointing has no control about the blind texts</a></h3>\r\n");
      out.write("                      </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 ftco-animate\">\r\n");
      out.write("            <div class=\"blog-entry\" data-aos-delay=\"100\">\r\n");
      out.write("              <a href=\"/NHMP/views/main/blog-single.html\" class=\"block-20\" style=\"background-image: url(/NHMP/resources/Main/images/image_2.jpg);\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"text text-center py-3\">\r\n");
      out.write("                <div class=\"meta mb-2\">\r\n");
      out.write("                  <div><a href=\"#\">Aug 5, 2019</a></div>\r\n");
      out.write("                  <div><a href=\"#\">Admin</a></div>\r\n");
      out.write("                  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"desc\">\r\n");
      out.write("                        <h3 class=\"heading\"><a href=\"#\">Even the all-powerful Pointing has no control about the blind texts</a></h3>\r\n");
      out.write("                      </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 ftco-animate\">\r\n");
      out.write("            <div class=\"blog-entry\" data-aos-delay=\"200\">\r\n");
      out.write("              <a href=\"/NHMP/views/main/blog-single.html\" class=\"block-20\" style=\"background-image: url(/NHMP/resources/Main/images/image_3.jpg);\">\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"text text-center py-3\">\r\n");
      out.write("                <div class=\"meta mb-2\">\r\n");
      out.write("                  <div><a href=\"#\">Aug 5, 2019</a></div>\r\n");
      out.write(" \t\t\t\t  <div><a href=\"#\">Admin</a></div>\r\n");
      out.write("                  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"desc\">\r\n");
      out.write("                        <h3 class=\"heading\"><a href=\"#\">Even the all-powerful Pointing has no control about the blind texts</a></h3>\r\n");
      out.write("                      </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write(" -->\r\n");
      out.write("    <footer class=\"ftco-footer ftco-bg-dark ftco-section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row mb-5\">\r\n");
      out.write("          <div class=\"col-md\">\r\n");
      out.write("            <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("              <h2 class=\"ftco-heading-2\">Ignite</h2>\r\n");
      out.write("              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("              <ul class=\"ftco-footer-social list-unstyled mb-0\">\r\n");
      out.write("                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-twitter\"></span></a></li>\r\n");
      out.write("                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-facebook\"></span></a></li>\r\n");
      out.write("                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-instagram\"></span></a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md\">\r\n");
      out.write("            <div class=\"ftco-footer-widget mb-4 ml-md-5\">\r\n");
      out.write("              <h2 class=\"ftco-heading-2\">Unseful Links</h2>\r\n");
      out.write("              <ul class=\"list-unstyled\">\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Servers</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Windos Hosting</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Cloud Hosting</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">OS Servers</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Linux Servers</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Policy</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md\">\r\n");
      out.write("             <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("              <h2 class=\"ftco-heading-2\">Navigational</h2>\r\n");
      out.write("              <ul class=\"list-unstyled\">\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Home</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Domain</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Hosting</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">About</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Blog</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"py-2 d-block\">Contact</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md\">\r\n");
      out.write("            <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("                <h2 class=\"ftco-heading-2\">Office</h2>\r\n");
      out.write("                <div class=\"block-23 mb-3\">\r\n");
      out.write("                      <ul>\r\n");
      out.write("                        <li><span class=\"icon icon-map-marker\"></span><span class=\"text\">203 Fake St. Mountain View, San Francisco, California, USA</span></li>\r\n");
      out.write("                        <li><a href=\"#\"><span class=\"icon icon-phone\"></span><span class=\"text\">+2 392 3929 210</span></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><span class=\"icon icon-envelope\"></span><span class=\"text\">info@yourdomain.com</span></a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"icon-heart\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- loader -->\r\n");
      out.write("  <div id=\"ftco-loader\" class=\"show fullscreen\"><svg class=\"circular\" width=\"48px\" height=\"48px\"><circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke=\"#eeeeee\"/><circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\" stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\"/></svg></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script src=\"resources/Main/js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/Main/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/Main/js/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/Main/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/Main/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("  <script src=\"resources/Main/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/Main/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/Main/js/owl.carousel.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/Main/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/Main/js/aos.js\"></script>\r\n");
      out.write("  <script src=\"resources/Main/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/Main/js/scrollax.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false\"></script>\r\n");
      out.write("  <script src=\"resources/Main/js/google-map.js\"></script>\r\n");
      out.write("  <script src=\"resources/Main/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("       ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
