/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-10-26 08:10:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.ERP.PaySum;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Main.NursingHospital.model.ov.NursingHospital;
import java.util.ArrayList;
import ERP.Deduction.model.vo.Deduction;
import ERP.Allowance.model.vo.Allowance;
import ERP.Employee.model.vo.Employee;

public final class PaySum_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Main.NursingHospital.model.ov.NursingHospital");
    _jspx_imports_classes.add("ERP.Employee.model.vo.Employee");
    _jspx_imports_classes.add("ERP.Deduction.model.vo.Deduction");
    _jspx_imports_classes.add("ERP.Allowance.model.vo.Allowance");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	NursingHospital loginHospital = (NursingHospital)session.getAttribute("loginHospital");
	ArrayList<Allowance> Alist = (ArrayList<Allowance>)request.getAttribute("Alist");
	ArrayList<Deduction> Dlist = (ArrayList<Deduction>)request.getAttribute("Dlist");
	ArrayList<Employee> Elist = (ArrayList<Employee>)request.getAttribute("Elist");
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\r\n");
      out.write("<title>TMTS</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#rootdiv{\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\twidth:1100px;\r\n");
      out.write("\t\theight:auto;\r\n");
      out.write("\t\t/* border : 1px solid red; */\r\n");
      out.write("\t\tmargin:40px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#rootdiv #Paylist div{\r\n");
      out.write("\t\theight:250px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#rootdiv #Payleft{\r\n");
      out.write("\t\t/* border : 1px solid red; */\r\n");
      out.write("\t\tfloat: left; \r\n");
      out.write("\t\twidth: 40%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#rootdiv #Payleft table{\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tbackground:#f4f4f4;\r\n");
      out.write("\t\tcolor:#000;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#rootdiv #Payleft table th{\r\n");
      out.write("\t\tbackground: rgb(117, 113, 249, 0.5);\r\n");
      out.write("    \tcolor:rgba(0, 0, 0, 1);\r\n");
      out.write("    \ttext-align:center;\r\n");
      out.write("    \t/* opacity:0.5; */\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t#rootdiv #Paycenter{\r\n");
      out.write("\t\t/* border : 1px solid red; */\r\n");
      out.write("\t\tfloat: right; \r\n");
      out.write("\t\twidth: 300px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#rootdiv #Paycenter table{\r\n");
      out.write("\t\twidth:290px;\r\n");
      out.write("\t\tfloat:right;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tbackground:#f4f4f4;\r\n");
      out.write("\t\tcolor:#000;\r\n");
      out.write("\t}\r\n");
      out.write("\t#rootdiv #Paycenter table th{\r\n");
      out.write("\t\tbackground: rgb(117, 113, 249, 0.5);\r\n");
      out.write("    \ttext-align:center;\r\n");
      out.write("    \tcolor:rgba(0, 0, 0, 1);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t#rootdiv #Payright{\r\n");
      out.write("\t\t/* border : 1px solid red; */\r\n");
      out.write("\t\tfloat: right; \r\n");
      out.write("\t\twidth: 30%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#rootdiv #Payright table{\r\n");
      out.write("\t\twidth:290px;\r\n");
      out.write("\t\tfloat:right;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tbackground:#f4f4f4;\r\n");
      out.write("\t\tcolor:#000;\r\n");
      out.write("\t}\r\n");
      out.write("\t#rootdiv #Payright table th{\r\n");
      out.write("\t\tbackground: rgb(117, 113, 249, 0.5);\r\n");
      out.write("    \ttext-align:center;\r\n");
      out.write("    \tcolor:rgba(0, 0, 0, 1);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#rootdiv div{\r\n");
      out.write("\t\theight:300px;\r\n");
      out.write("\t\tborder:0px;\r\n");
      out.write("\t\tmargin:0px;\r\n");
      out.write("\t\tpadding:0px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#rootdiv #Payresult {\r\n");
      out.write("\t\tmargin:0%;\r\n");
      out.write("\t\tfloat:right;\r\n");
      out.write("\t}\t\r\n");
      out.write("\t#rootdiv #Payresult table{\r\n");
      out.write("\t\tmargin-left:10px;\r\n");
      out.write("\t\twidth:290px;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tbackground:#f4f4f4;\r\n");
      out.write("\t\tcolor:#000;\r\n");
      out.write("\t}\r\n");
      out.write("\t#rootdiv #Payresult table th{\r\n");
      out.write("\t\tbackground: rgb(117, 113, 249, 0.5);\r\n");
      out.write("\t\twidth:129px;\r\n");
      out.write("    \ttext-align:center;\r\n");
      out.write("    \tcolor:rgba(0, 0, 0, 1);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/NHMP/resources/common/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var payresult = \"\";\r\n");
      out.write("var Ecnt = 0;\r\n");
      out.write("var totalresult = \"0\";\r\n");
      out.write("var totalresultA = \"0\";\r\n");
      out.write("\r\n");
      out.write("function Echeckbox(empid){\r\n");
      out.write("\tvar thispuls = \"ECheckBtn\"+empid;\r\n");
      out.write("\tvar id = \"\";\r\n");
      out.write("\ttotalresult = 0;\r\n");
      out.write("\tif( ($(\"#\"+thispuls).prop('checked')) ){\r\n");
      out.write("\t\tif($(\"#pay\").val() == 0 ){\r\n");
      out.write("\t\t\tEcnt=1;\r\n");
      out.write("\t\t\tid = empid;\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"/NHMP/getpay\",\r\n");
      out.write("\t\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\t\tdata : {empid : empid},\r\n");
      out.write("\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data.salary);\r\n");
      out.write("\t\t\t\t\t$(\"#pay\").val(data.salary);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}, error : function(jqXHR, textStatus, errorThrown ){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"error : \" + jqXHR + \", \" + textStatus + \", \" +errorThrown);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tEcnt=1;\r\n");
      out.write("\t\t\t$('input[type=\"text\"]').val(0);\r\n");
      out.write("\t\t\t$('input[type=\"checkbox\"][class=\"CECheckBtn\"]').prop('checked', false);\r\n");
      out.write("\t\t\t$('input[type=\"checkbox\"][class=\"DCheckBtn\"]').prop('checked', false);\r\n");
      out.write("\t\t\t$('input[type=\"checkbox\"][class=\"ACheckBtn\"]').prop('checked', false);\r\n");
      out.write("\t\t\t$(\"#\"+thispuls).prop('checked',true);\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"/NHMP/getpay\",\r\n");
      out.write("\t\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\t\tdata : {empid : empid},\r\n");
      out.write("\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data.salary);\r\n");
      out.write("\t\t\t\t\t$(\"#pay\").val(data.salary);\r\n");
      out.write("\t\t\t\t}, error : function(jqXHR, textStatus, errorThrown ){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"error : \" + jqXHR + \", \" + textStatus + \", \" +errorThrown);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$('input[type=\"checkbox\"][class=\"CECheckBtn\"]').prop('checked', false);\r\n");
      out.write("\t\t$('input[type=\"checkbox\"][class=\"DCheckBtn\"]').prop('checked', false);\r\n");
      out.write("\t\t$('input[type=\"checkbox\"][class=\"ACheckBtn\"]').prop('checked', false);\r\n");
      out.write("\t\t$('input[type=\"text\"]').val(0);\r\n");
      out.write("\t\tEcnt=0;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function Dcheckbox(Dcode, Dno){\r\n");
      out.write("\tif($(\"#pay\").val() != 0){\r\n");
      out.write("\t\tvar payD = \"#payD\";\r\n");
      out.write("\t\tvar Did = \"DCheckBtn\"+Dno;\r\n");
      out.write("\t\tpayresult = payD+Dno;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"/NHMP/getdeduc\",\r\n");
      out.write("\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\tdata : {Dcode : Dcode},\r\n");
      out.write("\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar pay = $(\"#pay\").val();\r\n");
      out.write("\t\t\t\tvar resultformula = data.replace(\"T01\", pay);\r\n");
      out.write("\t\t\t\tvar result = Math.floor(eval(resultformula)/10)*10;\r\n");
      out.write("\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\tif($(\"#\"+Did).prop('checked')){\r\n");
      out.write("\t\t\t\t\ttotalresult = eval(eval(totalresult)+eval(result));\r\n");
      out.write("\t\t\t\t\tconsole.log(\"totalresult : \"+totalresult);\r\n");
      out.write("\t\t\t\t\tconsole.log(\"result : \"+result);\r\n");
      out.write("\t\t\t\t\t$(payresult).val(result);\r\n");
      out.write("\t\t\t\t\t$(\"#totalD\").val(totalresult);\r\n");
      out.write("\t\t\t\t\t$(\"#totalM\").val(eval(eval(pay)-eval(totalresult)+eval(totalresultA)));\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\ttotalresult = eval(eval(totalresult)-eval(result));\r\n");
      out.write("\t\t\t\t\t$(payresult).val(0);\r\n");
      out.write("\t\t\t\t\t$(\"#totalD\").val(totalresult);\r\n");
      out.write("\t\t\t\t\t$(\"#totalM\").val( eval( eval($(\"#totalM\").val())+eval(result) ) );\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}, error : function(jqXHR, textStatus, errorThrown ){\r\n");
      out.write("\t\t\t\tconsole.log(\"error : \" + jqXHR + \", \" + textStatus + \", \" +errorThrown);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"한명의 직원을 선택하여 주세요\");\r\n");
      out.write("\t\t$('input[type=\"checkbox\"][class=\"DCheckBtn\"]').prop('checked', false);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function Acheckbox(Acode, Ano){\r\n");
      out.write("\tif($(\"#pay\").val() != 0){\r\n");
      out.write("\t\tvar payA = \"#payA\";\r\n");
      out.write("\t\tvar Aid = \"ACheckBtn\"+Ano;\r\n");
      out.write("\t\tpayresult = payA+Ano;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"/NHMP/getallow\",\r\n");
      out.write("\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\tdata : {Acode : Acode},\r\n");
      out.write("\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar pay = $(\"#pay\").val();\r\n");
      out.write("\t\t\t\tvar resultformula = data.replace(\"T01\", pay);\r\n");
      out.write("\t\t\t\tvar resultA = Math.floor(eval(resultformula)/10)*10;\r\n");
      out.write("\t\t\t\tif($(\"#\"+Aid).prop('checked')){\r\n");
      out.write("\t\t\t\t\ttotalresultA = eval(eval(totalresultA)+eval(resultA));\r\n");
      out.write("\t\t\t\t\t$(payresult).val(resultA);\r\n");
      out.write("\t\t\t\t\t$(\"#totalA\").val(totalresultA);\r\n");
      out.write("\t\t\t\t\t$(\"#totalM\").val( eval(eval($(\"#pay\").val())-eval($(\"#totalD\").val())+eval($(\"#totalA\").val())) )  ;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\ttotalresultA = eval(eval(totalresultA)-eval(resultA));\r\n");
      out.write("\t\t\t\t\t$(payresult).val(0);\r\n");
      out.write("\t\t\t\t\t$(\"#totalA\").val(totalresultA);\r\n");
      out.write("\t\t\t\t\t$(\"#totalM\").val( eval(eval($(\"#pay\").val())-eval($(\"#totalD\").val())+eval($(\"#totalA\").val())));\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}, error : function(jqXHR, textStatus, errorThrown ){\r\n");
      out.write("\t\t\t\tconsole.log(\"error : \" + jqXHR + \", \" + textStatus + \", \" +errorThrown);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"한명의 직원을 선택하여 주세요\");\r\n");
      out.write("\t\t$('input[type=\"checkbox\"][class=\"DCheckBtn\"]').prop('checked', false);\r\n");
      out.write("\t\t$('input[type=\"checkbox\"][class=\"ACheckBtn\"]').prop('checked', false);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Favicon icon -->\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\"\r\n");
      out.write("\thref=\"/NHMP/resources/ERP/images/common/favicon.png\">\r\n");
      out.write("<!-- Pignose Calender -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"/NHMP/resources/ERP/css/plugins/pg-calendar/css/pignose.calendar.min.css?after\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!-- Chartist -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/NHMP/resources/ERP/css/plugins/chartist/css/chartist.min.css?after\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/NHMP/resources/ERP/css/plugins/chartist-plugin-tooltips/css/chartist-plugin-tooltip.css?after\">\r\n");
      out.write("<!-- Custom Stylesheet -->\r\n");
      out.write("<link href=\"/NHMP/resources/ERP/css/style.css?after\" rel=\"stylesheet\">\r\n");
      out.write("<!-- icon CDN 방식 적용 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!--*******************\r\n");
      out.write("        Preloader start\r\n");
      out.write("    ********************-->\r\n");
      out.write("\t<div id=\"preloader\">\r\n");
      out.write("\t\t<div class=\"loader\">\r\n");
      out.write("\t\t\t<svg class=\"circular\" viewBox=\"25 25 50 50\">\r\n");
      out.write("                <circle class=\"path\" cx=\"50\" cy=\"50\" r=\"20\" fill=\"none\"\r\n");
      out.write("\t\t\t\t\tstroke-width=\"3\" stroke-miterlimit=\"10\" />\r\n");
      out.write("            </svg>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--*******************\r\n");
      out.write("        Preloader end\r\n");
      out.write("    ********************-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--**********************************\r\n");
      out.write("        Main wrapper start\r\n");
      out.write("    ***********************************-->\r\n");
      out.write("\t<div id=\"main-wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!--**********************************\r\n");
      out.write("            Nav header start\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\t\t<div class=\"nav-header\">\r\n");
      out.write("\t\t\t<div class=\"brand-logo\">\r\n");
      out.write("\t\t\t\t<a href=\"/NHMP/views/ERP/main.jsp\"> <b class=\"logo-abbr\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/NHMP/resources/ERP/images/common/logo.png\" alt=\"\"> </b> <span\r\n");
      out.write("\t\t\t\t\tclass=\"logo-compact\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/NHMP/resources/ERP/images/common/logo-compact.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"brand-title\"> <img align=\"middle\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/NHMP/resources/ERP/images/common/logo-text.png\" ailgn=\"\">\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--**********************************\r\n");
      out.write("            Nav header end\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--**********************************\r\n");
      out.write("            Header start\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t<div class=\"header-content clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"nav-control\">\r\n");
      out.write("\t\t\t\t\t<div class=\"hamburger\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"toggle-icon\"><i class=\"icon-menu\"></i></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"header-left\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group icons\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group-prepend\">\r\n");
      out.write("\t\t\t\t\t\t\t<span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"input-group-text bg-transparent border-0 pr-2 pr-sm-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"basic-addon1\"><i class=\"mdi mdi-magnify\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"search\" class=\"form-control\" placeholder=\"검색할 메뉴 명\"\r\n");
      out.write("\t\t\t\t\t\t\taria-label=\"Search Dashboard\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"drop-down animated flipInX d-md-none\">\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Search\">\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"header-right\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"icons dropdown\"><a href=\"javascript:void(0)\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"dropdown\"> <i class=\"mdi mdi-email-outline\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"badge badge-pill gradient-1\">3</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"drop-down animated fadeIn dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"dropdown-content-heading d-flex justify-content-between\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"\">3 New Messages</span> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"javascript:void()\" class=\"d-inline-block\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"badge badge-pill gradient-1\">3</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dropdown-content-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"notification-unread\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"javascript:void()\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"float-left mr-3 avatar-img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"/NHMP/resources/ERP/images/avatar/1.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-heading\">Saiful Islam</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-timestamp\">08 Hours ago</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-text\">Hi Teddy, Just wanted\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tto let you ...</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"notification-unread\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"javascript:void()\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"float-left mr-3 avatar-img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"/NHMP/resources/ERP/images/avatar/2.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-heading\">Adam Smith</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-timestamp\">08 Hours ago</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-text\">Can you do me a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tfavour?</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"javascript:void()\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"float-left mr-3 avatar-img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"/NHMP/resources/ERP/images/avatar/3.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-heading\">Barak Obama</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-timestamp\">08 Hours ago</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-text\">Hi Teddy, Just wanted\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tto let you ...</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"javascript:void()\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"float-left mr-3 avatar-img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"/NHMP/resources/ERP/images/avatar/4.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-heading\">Hilari Clinton</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-timestamp\">08 Hours ago</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-text\">Hello</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"icons dropdown\"><a href=\"javascript:void(0)\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"dropdown\"> <i class=\"mdi mdi-bell-outline\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"badge badge-pill gradient-2\">3</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"drop-down animated fadeIn dropdown-menu dropdown-notfication\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"dropdown-content-heading d-flex justify-content-between\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"\">2 New Notifications</span> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"javascript:void()\" class=\"d-inline-block\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"badge badge-pill gradient-2\">5</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dropdown-content-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"javascript:void()\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"mr-3 avatar-icon bg-success-lighten-2\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"icon-present\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"notification-heading\">Events near you</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"notification-text\">Within next 5 days</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"javascript:void()\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"mr-3 avatar-icon bg-danger-lighten-2\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"icon-present\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"notification-heading\">Event Started</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"notification-text\">One hour ago</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"javascript:void()\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"mr-3 avatar-icon bg-success-lighten-2\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"icon-present\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"notification-heading\">Event Ended\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tSuccessfully</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"notification-text\">One hour ago</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"javascript:void()\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"mr-3 avatar-icon bg-danger-lighten-2\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"icon-present\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"notification-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"notification-heading\">Events to Join</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"notification-text\">After two days</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"icons dropdown d-none d-md-flex\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:void(0)\" class=\"log-user\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>korean</span> <i class=\"fa fa-angle-down f-s-14\"\r\n");
      out.write("\t\t\t\t\t\t\t\taria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"drop-down dropdown-language animated fadeIn  dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dropdown-content-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"javascript:void()\">English</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"javascript:void()\">Korean</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"icons dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"user-img c-pointer position-relative\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"activity active\"></span> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"/NHMP/resources/ERP/images/user/1.png\" height=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth=\"40\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"drop-down dropdown-profile animated fadeIn dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dropdown-content-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"app-profile.html\"><i class=\"icon-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span>마이페이지</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"javascript:void()\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"icon-envelope-open\"></i> <span>Inbox</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"badge gradient-3 badge-pill gradient-1\">3</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<hr class=\"my-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"page-lock.html\"><i class=\"icon-lock\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span>Lock Screen</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"page-login.html\"><i class=\"icon-key\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span>Logout</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--**********************************\r\n");
      out.write("            Header end ti-comment-alt\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--**********************************\r\n");
      out.write("            Sidebar start\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\t\t<div class=\"nk-sidebar\">\r\n");
      out.write("\t\t\t<div class=\"nk-nav-scroll\">\r\n");
      out.write("\t\t\t\t<ul class=\"metismenu\" id=\"menu\">\r\n");
      out.write("\t\t\t\t\t<li class=\"mega-menu mega-menu-sm\"><a class=\"has-arrow\"\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:void()\" aria-expanded=\"false\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-users\"></i><span class=\"nav-text\">인사관리</span> <!-- <i class=\"icon-globe-alt menu-icon\"></i><span class=\"nav-text\">인사설정</span>-->\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<ul aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"layout-blank.html\">인사정보관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"layout-one-column.html\">인사정보등록</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"layout-two-column.html\">조직도</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"has-arrow\" href=\"javascript:void()\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\"> <i class=\"fa fa-id-card\"></i> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-text\">권한설정</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t");
 if(loginHospital != null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/NHMP/authall\">권한부여관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"has-arrow\" href=\"javascript:void()\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\"> <i class=\"fa fa-plus-square\"></i><span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-text\">환자 관리</span> <!--   <i class=\"icon-screen-tablet menu-icon\"></i><span class=\"nav-text\">환자 관리</span> -->\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"app-profile.html\">전체환자 조회</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"app-calender.html\">환자 입원 등록</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"app-calender.html\">상담일지 등록</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"app-calender.html\">투약일지 등록</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li><a class=\"has-arrow\" href=\"javascript:void()\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\"> <i class=\"fa fa-usd\"></i><span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-text\">급여 관리</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<ul aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/NHMP/deduclise\">공제항목등록</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/NHMP/allowlist\">수당항목등록</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/NHMP/paylistD\">급여계산</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"javascript:void()\" aria-expanded=\"false\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-slideshare\"></i> <span class=\"nav-text\">공지사항</span>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"javascript:void()\" aria-expanded=\"false\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-download\"></i> <span class=\"nav-text\">자료실</span>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--**********************************\r\n");
      out.write("            Sidebar end\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--**********************************\r\n");
      out.write("            Content body start\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\t\t<div class=\"content-body\">\r\n");
      out.write("\t\t\t<div id=\"rootdiv\">\r\n");
      out.write("\t\t\t\t<form action=\"\">\r\n");
      out.write("\t\t\t\t\t<br> <br>\r\n");
      out.write("\t\t\t\t\t<div id=\"Paylist\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"Payleft\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<table border=\"1\" margin=\"0 0 0 0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>선택</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>사번</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									for (Employee e : Elist) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"ECheckBtn\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"ECheckBtn");
      out.print(e.getEmpId());
      out.write("\" class=\"CECheckBtn\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"Echeckbox('");
      out.print(e.getEmpId());
      out.write("')\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"text-align: center; vertical-align: middle; width: 1.0rem; height: 1.0rem\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(e.getEmpName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(e.getEmpId());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 디비에서 list 받아서 가져오기 -->\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- Payleft -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div id=\"Paycenter\">\r\n");
      out.write("\t\t\t\t\t\t\t<table width=\"auto\" border=\"1\" margin=\"0 0 0 0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>선택</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th align=\"center\">공제명칭1</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									for (Deduction d : Dlist) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" class=\"DCheckBtn\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"DCheckBtn");
      out.print(d.getDEDUCTION_NO());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"Dcheckbox('");
      out.print(d.getDEDUCTION_CODE());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(d.getDEDUCTION_NO());
      out.write("')\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"text-align: center; vertical-align: middle; width: 1.0rem; height: 1.0rem\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(d.getDEDUCTION_NAME());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 디비에서 list 받아서 가져오기 -->\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- Paycenter -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div id=\"Payright\">\r\n");
      out.write("\t\t\t\t\t\t\t<table width=\"auto\" border=\"1\" margin=\"0 0 0 0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>선택</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th align=\"center\">수당명칭2</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									for (Allowance a : Alist) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" class=\"ACheckBtn\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"ACheckBtn");
      out.print( a.getALLOWANCE_NO() );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"Acheckbox('");
      out.print( a.getALLOWANCE_CODE() );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( a.getALLOWANCE_NO() );
      out.write("')\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"text-align: center; vertical-align: middle; width: 1.0rem; height: 1.0rem\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(a.getALLOWANCE_NAME());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 디비에서 list 받아서 가져오기 -->\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- Payright -->\r\n");
      out.write("\t\t\t\t\t\t<div id=\"Payresult\">\r\n");
      out.write("\t\t\t\t\t\t\t<table border=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"Payresult\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table border=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											for (Allowance a : Alist) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th style=\"text-align: center;\">");
      out.print(a.getALLOWANCE_NAME());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"text-align: center;\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"payA");
      out.print( a.getALLOWANCE_NO() );
      out.write("\" class=\"CpayA\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"0\" style=\"text-align: right; width: 140px;\" readonly>원\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												}
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th style=\"text-align: center;\">수당총액\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"text-align: center;\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"totalA\" value=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"text-align: right; width: 140px;\" readonly>원\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th style=\"text-align: center;\">월수령액\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"text-align: center;\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"totalM\" value=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"text-align: right; width: 140px;\" readonly>원\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"Payresult\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table border=\"1\" id=\"resultwindow\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

											for (Deduction d : Dlist) {
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th style=\"text-align: center;\">");
      out.print(d.getDEDUCTION_NAME());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"text-align: center;\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"payD");
      out.print(d.getDEDUCTION_NO());
      out.write("\" class=\"CpayD\" value=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"text-align: right; width: 140px;\" readonly>원\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

												}
											
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th style=\"text-align: center;\">공제총액\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"text-align: center;\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"totalD\" value=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"text-align: right; width: 140px;\" readonly>원\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th style=\"text-align: center;\">기본급\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"text-align: center;\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"pay\" value=\"0\" style=\"text-align: right; width: 140px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treadonly>원</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--**********************************\r\n");
      out.write("            Content body end\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--**********************************\r\n");
      out.write("            Footer start\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\t\t\t<div class=\"footer\">\r\n");
      out.write("\t\t\t\t<div class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\tCopyright &copy; Designed & Developed by <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://themeforest.net/user/quixlab\">이민삼수</a> 2019\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--**********************************\r\n");
      out.write("            Footer end\r\n");
      out.write("        ***********************************-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--**********************************\r\n");
      out.write("        Main wrapper end\r\n");
      out.write("    ***********************************-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--**********************************\r\n");
      out.write("        Scripts\r\n");
      out.write("    ***********************************-->\r\n");
      out.write("\t\t<script src=\"/NHMP/resources/ERP/css/plugins/common/common.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"/NHMP/resources/ERP/js/custom.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"/NHMP/resources/ERP/js/settings.js\"></script>\r\n");
      out.write("\t\t<script src=\"/NHMP/resources/ERP/js/gleek.js\"></script>\r\n");
      out.write("\t\t<script src=\"/NHMP/resources/ERP/js/styleSwitcher.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Chartjs -->\r\n");
      out.write("\t\t<script\r\n");
      out.write("\t\t\tsrc=\"/NHMP/resources/ERP/css/plugins/chart.js/Chart.bundle.min.js\"></script>\r\n");
      out.write("\t\t<!-- Circle progress -->\r\n");
      out.write("\t\t<script\r\n");
      out.write("\t\t\tsrc=\"/NHMP/resources/ERP/css/plugins/circle-progress/circle-progress.min.js\"></script>\r\n");
      out.write("\t\t<!-- Datamap -->\r\n");
      out.write("\t\t<script src=\"/NHMP/resources/ERP/css/plugins/d3v3/index.js\"></script>\r\n");
      out.write("\t\t<script src=\"/NHMP/resources/ERP/css/plugins/topojson/topojson.min.js\"></script>\r\n");
      out.write("\t\t<script\r\n");
      out.write("\t\t\tsrc=\"/NHMP/resources/ERP/css/plugins/datamaps/datamaps.world.min.js\"></script>\r\n");
      out.write("\t\t<!-- Morrisjs -->\r\n");
      out.write("\t\t<script src=\"/NHMP/resources/ERP/css/plugins/raphael/raphael.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"/NHMP/resources/ERP/css/plugins/morris/morris.min.js\"></script>\r\n");
      out.write("\t\t<!-- Pignose Calender -->\r\n");
      out.write("\t\t<script src=\"/NHMP/resources/ERP/css/plugins/moment/moment.min.js\"></script>\r\n");
      out.write("\t\t<script\r\n");
      out.write("\t\t\tsrc=\"/NHMP/resources/ERP/css/plugins/pg-calendar/js/pignose.calendar.min.js\"></script>\r\n");
      out.write("\t\t<!-- ChartistJS -->\r\n");
      out.write("\t\t<script\r\n");
      out.write("\t\t\tsrc=\"/NHMP/resources/ERP/css/plugins/chartist/js/chartist.min.js\"></script>\r\n");
      out.write("\t\t<script\r\n");
      out.write("\t\t\tsrc=\"/NHMP/resources/ERP/css/plugins/chartist-plugin-tooltips/js/chartist-plugin-tooltip.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"/NHMP/resources/ERP/js/dashboard/dashboard-1.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
