DROP TABLE ALLOWANCE;
DROP TABLE CAREER;
DROP TABLE CNOTICE;
DROP TABLE COMMENTS;
DROP TABLE COUNSELINGLOG;
DROP TABLE CREGISTRATION;
DROP TABLE DATAROOM;
DROP TABLE DEDUCTION;
DROP TABLE DEPARTMENT;
DROP TABLE DEPENDENTS;
DROP TABLE EDUCATION;
DROP TABLE EMPLOYEE;
DROP TABLE EMPMENT;
DROP TABLE MEDICIENRECORD;
DROP TABLE NOTICE;
DROP TABLE NURSING_HOSPITAL;
DROP TABLE QNA;
DROP TABLE TEAM;
DROP TABLE WARD;
DROP TABLE CALENDAR;


DROP TABLE AUTHORITY;
DROP TABLE EMPLOYEE;
DROP TABLE PATIENT;
DROP TABLE POSITIONS;
DROP TABLE CAUTHORITY;
DROP TABLE HOLD_OFFICE;
DROP TABLE EMPMENT;
DROP TABLE EMPSALARY;
DROP TABLE SERVICE;

DROP SEQUENCE SEQ_EMP_ID;
DROP SEQUENCE DATAROOM_SEQ;
DROP SEQUENCE NOTICE_SEQ;
DROP SEQUENCE PAT_SEQ;
DROP SEQUENCE MR_SEQ;
DROP SEQUENCE CL_SEQ;
DROP SEQUENCE SEQ_CAL;
DROP SEQUENCE SEQ_CNOTICE;
DROP SEQUENCE SEQ_QNA;
DROP SEQUENCE CAR_SEQ_CODE;
DROP SEQUENCE DPEN_SEQ_CODE;
DROP SEQUENCE EDU_SEQ_CODE;

DROP PROCEDURE NEWUSER;
drop user user02 CASCADE;
